### ISSUE TITLE
update compatibility for KSP 1.2 and 1.3!

### ISSUE THREAD

**Issue by rvalle7** [Vivero/Kerbal-VR#11]
Hey man, this is super. I have Oculus Rift DK1 on Mac, and will love to test it here, but only if it can be ported to KSP 1.2 and 1.3. So, please, please please, continue evolving!

**Comment by Vivero** [comment]
See [release 2.0.3](https://github.com/Vivero/Kerbal-VR/releases/tag/v2.0.3), it is now compatible with KSP 1.4. Thanks for your interest!
