### ISSUE TITLE
Incredibly spazzy camera

### ISSUE THREAD

**Issue by Wazbat** [Vivero/Kerbal-VR#12]
Trying to use this on KSP 1.1.0
Tracking works great though everything seems huge. But the camera on screen while low fps is ok, but the actual tracking camera seems to spaz around like mad making it unbearable. The look angle constantly flickers to the sides

**Comment by Vivero** [comment]
Can't tell if this is a Vive tracking issue. Can you try with the latest release and see if the issue still exists?

**Comment by Vivero** [comment]
Closed until further description provided.
