### ISSUE TITLE
Build Instruktion

### ISSUE THREAD

**Issue by X52p** [Vivero/Kerbal-VR#13]
I would like to build the project myself to try out some things, but I could't find out which libraries are missing. What do I need to build it my self?

**Comment by ZNixian** [comment]
Add a reference path of `...\Kerbal Space Program\KSP_x64_Data\Managed\`, depending on your KSP location.

**Comment by Vivero** [comment]
Yes the steps @ZNixian provided should be enough to build the project. Please let me know otherwise.
