### ISSUE TITLE
Nothing is working!!!

### ISSUE THREAD

**Issue by maxcaplan** [Vivero/Kerbal-VR#14]
I've followed your install instructions through 100 times over. But whenever I press Y in IVA, my headset stays in the steamVr home

**Comment by Vivero** [comment]
I know this is a shitty answer, but without more information, all I can say is "well it works on my machine...".

Try these instructions:

https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide

**Comment by Vivero** [comment]
Closing until further information can be provided.
