### ISSUE TITLE
Noticeable delay between head movement and actual headset display

### ISSUE THREAD

**Issue by Vivero** [Vivero/Kerbal-VR#18]
There seems to be some amount of delay in between obtaining the position of tracked devices (the headset) and the corresponding images displayed on the screen. It's like a small lag between physical movement and image display. It's noticeable enough that it is a bit dizzying.

Not sure how to solve this; I'm wondering if the tracked poses and frame rendering should be somewhere other than in LateUpdate. Where _should_ the OpenVR calls to Submit frames be called then?

**Comment by Vivero** [comment]
Actually, incorporating a secondsToPhotons delay value in the call to `GetDeviceToAbsoluteTrackingPose` seems to solve this problem. I just need to RTFM... https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetDeviceToAbsoluteTrackingPose

**Comment by Vivero** [comment]
Closed via #20

**Comment by jakeledoux** [comment]
I'm still experiencing this delay on KSP 1.4.3 with the latest version of this mod. Everything is smooth as butter but the delay is sickening.

If you need any more information like SteamVR versions and such let me know.

**Comment by Vivero** [comment]
Interesting... ok. Yea let me know what SteamVR version you are running. I'll see what I can find.

**Comment by jakeledoux** [comment]
I'm running version 1527117754 built May 23, 2018. I was on the beta previously but I switched so I could run X-Plane 11. I still had the problem back then as well, but I can always jump back on the beta if you need me to.

Other info:

Thing |  Details
------------ | -------------
CPU | i7-7700k
Graphics card | GTX 1070 Founders Edition
Graphics drivers | v397.64
RAM | 16gb of DDR4 in 2x8 configuration.

**Comment by Vivero** [comment]
Please re-open if this is still an issue on the latest versions of KSP and KerbalVR.

**Comment by jakeledoux** [comment]
Just installed the latest release on the newest version of KSP with both DLC. Same problem, unfortunately.

**Comment by Vivero** [comment]
:(

**Comment by Vivero** [comment]
I think this is fixed now: [latest release](https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.6)

**Comment by jakeledoux** [comment]
I’m definitely interested in trying this out when I have the time. I’ve been hyped to play this game in VR for 7 years now.
