### ISSUE TITLE
vr gui not showing when stram vr is open b4 game.??

### ISSUE THREAD

**Issue by taksuda** [Vivero/Kerbal-VR#21]
![capture](https://user-images.githubusercontent.com/29102678/37327915-169c4b8e-2690-11e8-9aaa-22ae61c8866c.PNG)

if game starts before the steam vr. it show the gui but no vr.. :( 

ps happy to do team viewer!! 👍

**Comment by Vivero** [comment]
Can you show me the full `KSP.log` file? I want to see if there were any error messages printed by the KerbalVR mod.

**Comment by taksuda** [comment]
[output_log.txt](https://github.com/Vivero/Kerbal-VR/files/1810968/output_log.txt)

sorry this is the only output log file that I can see. I am not sure how to make one

**Comment by taksuda** [comment]
ps if you want I can make a video showing you the issues. and post on YouTube?

**Comment by Vivero** [comment]
Please see the [Install Guide](https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide), you are running an outdated version of KSP.
