### ISSUE TITLE
[Non Issue] Microsoft MR test

### ISSUE THREAD

**Issue by rocketstrong600** [Vivero/Kerbal-VR#23]
i can confirm it works on my windows mixed reality headset with a rx480 as my gpu

**Comment by Vivero** [comment]
Nice, thanks so much for testing, I should start to include a note in the readme regarding what systems have been tested.

If anyone else sees this, leave a comment with your system specs so we know what works!

**Comment by Poldor** [comment]
HTC Vive, Windows 10, i5-4590, Geforce GTX 970

works just fine

**Comment by 9595w** [comment]
Windows Mixed Reality, Windows 10, i7-4790k, GeForce GTX 1070

Works with good FPS, controllers work too

**Comment by mrcheeze1** [comment]
Oculus Rift w/ touch controllers, Win10, i7-4790k, GTX 1080

Works like a charm.

**Comment by artwhaley** [comment]
It worked flawlessly on my laptop!   Windows 10, i5- 7300HQ GTX 1050 TI, with an HP WMR headset.  

I was even able to crank the resolution up to 1440x900 because I was hoping for a bit more legibility in the RPM screens.

**Comment by dsolmann** [comment]
HTC Vive,Windows 10, AMD Ryzen 7, GTX 1050 TI. Works fine

**Comment by Biotronic** [comment]
Oculus Rift, Win10, i7-8700K, 32GB RAM, 2x GTX 770. Framerate a bit low, but that's due to shoddy GPUs.

**Comment by ghost** [comment]
Oculus Rift, Win10, Ryzen 5 1400, 12GB DDR4 RAM, RX 580. Works. Can't really say about the framerate, as I used AVP and got lag, naturally.

**Comment by Vivero** [comment]
There's now an infinite combination of headsets, controllers, PC specs. Probably not worth keeping track of compatibility. It seems that whatever works with SteamVR will work with this mod (I think, maybe, who knows). Thanks everyone for your input!
