### ISSUE TITLE
Linux/MacOS support over OpenHMD

### ISSUE THREAD

**Issue by TheHellBox** [Vivero/Kerbal-VR#25]
Could we use OpenHMD instead of OpenVR to provide cross-platform(Mac, Linux, FreeBSD) VR support? The only problem is OpenHMD still doesn't have any kind of positional tracking support(Except Nolo support). Also it could require KSP render changes(We could spawn 2 cameras and 2 planes and render image into planes with distortion correction shaders).  If you want more info about OpenHMD, you can visit http://www.openhmd.net/ and github repo https://github.com/OpenHMD/OpenHMD

**Comment by ghost** [comment]
I have Arch Linux installed, along with an Oculus Rift I could test this with :+1:

**Comment by ghost** [comment]
Will this ever be considered, @Vivero

**Comment by TheHellBox** [comment]
At least we could add linux OpenVR support, SteamVR works on linux

**Comment by ghost** [comment]
however, if it was OpenVR only, then Rift wouldn't work

**Comment by TheHellBox** [comment]
Why? It must be fine with OpenHMD-SteamVR https://github.com/ChristophHaag/SteamVR-OpenHMD

**Comment by ghost** [comment]
because i'm pretty sure that's a SteamVR-only plugin that makes it work with OpenHMD

**Comment by TheHellBox** [comment]
OpenHMD support is not longer needed. OpenXR/OpenVR Linux support would be much better
