### ISSUE TITLE
Windows 7 guy

### ISSUE THREAD

**Issue by beedee12** [Vivero/Kerbal-VR#28]
Hola! I'm on Windows 7, and I have an Oculus, so my setup couldn't be more different from Vivero's, but maybe with my logs someone might be able to come up with a way to get it working? 
[error.log](https://github.com/Vivero/Kerbal-VR/files/1865402/error.log)
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/1865403/KSP.log)

Thanks for your time, and I'm happy to test any ideas or solutions you think of. Cheers!

**Comment by Vivero** [comment]
Hey thanks for checking in. I see one problem, you're running with the `-force-d3d11` flag. This for sure causes my mod to crash. You need to run with the `-force-d3d12` flag. Make sure to take a look at the [Install Guide](https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide).

Let me know how it goes.

**Comment by beedee12** [comment]
Will give it a go, though isn't DX12 only for Windows 10? I figured the d3d12 flag would either get ignored or make the computer confused haha

**Comment by Vivero** [comment]
Oh interesting. I don't know... if that's true, then I'm afraid Win7 can't be used with this mod :(

**Comment by beedee12** [comment]
Aaaargh! That's terrible news hahaha. Damn :( 
What are the odds of my messing around with an earlier version of KSP and an earlier version of the mod, then? (thanks for taking a look in the first place, by the way!)

**Comment by Vivero** [comment]
Sure, I guess you can try it. The last version that was working was KSP v1.1.3 + [KerbalVR v2.0.2](https://github.com/Vivero/Kerbal-VR/releases/tag/v2.0.2). That version requires the `-force-d3d11` flag

**Comment by beedee12** [comment]
Thanks again for your time! That version insisted on forcing OpenGL but it works pretty nicely!
If at some time you're able to work with anyone who could help with Windows 7 compatibility, consider me a happy donator, this is really a great plugin. Cheers!

**Comment by Vivero** [comment]
Oh yes that's right, that version used opengl. Thanks for your support!

**Comment by ChristophHaag** [comment]
If you can switch to Vulkan, it does not only work on all windows versions (if there is a graphics driver with Vulkan support), it also works on Linux which would make an eventual Linux+SteamVR port much easier.

**Comment by Vivero** [comment]
I'm not sure how to force KSP to run with Vulkan drivers

**Comment by ChristophHaag** [comment]
That would be the still undocumented parameter `-force-vulkan`.

From the logs it looks like they are on Unity 2017.1.3p1, it could be that's a version where vulkan support isn't mature yet...

**Comment by barrybarrette** [comment]
I'm happy to help out if there are any roadblocks to working around the dx12 issue. Would really love to try this mod but absolutely not going to be using win10. Is there a specific API call you need in dx12 that isn't there in 11? Just curious about the reasoning for needing dx12, maybe there's an alternative solution?

**Comment by Vivero** [comment]
I really don't know; for starters, when running the mod on DX11, it just crashes on the first attempt to submit the render texture to the OpenVR API call that renders to the HMD. That submit call happens in the LateUpdate() routine of the KerbalVR mod. I think there's something about Unity's rendering pipeline under the hood that makes accessing the render textures finicky. It's just different in DX11 vs DX12.

**Comment by FeepingCreature** [comment]
I'm also in the "Windows 7; not intending to upgrade to 10 anytime soon" camp. Darn...

edit: It **actually works for me just fine** on Windows 7! No issues with `--force-d3d11`!

edit: Though it crashes after a minute with that flag :cry: Also all the parts have missing textures in the overview.

edit: backtrace removed, I was looking at the wrong file.

**Comment by Vivero** [comment]
@FeepingCreature I definitely remember seeing this crashing occur when using the `--force-d3d11` flag. That's why I didn't really want to advertise Win 7 compatibility if it was just going to crash like that.

However, I just did some brief testing again with KSP 1.6 and the latest KerbalVR release (v3.2.2), and it ran a little longer before crashing. More than a minute. So... it still crashed, but maybe worth a shot for you to retry. Let me know what you find.

**Comment by FeepingCreature** [comment]
No, that matches my experience. It just sounded like you were saying it didn't work at all.

**Comment by beedee12** [comment]
Heya, what do you make of this?

https://www.anandtech.com/show/14078/microsoft-brings-dx12-to-windows-7

Would that help us Windows 7 folk in future?

**Comment by Vivero** [comment]
Interesting, yes it's probable that being able to run DX12 in Win7 would make the mod simply work out of the box.

This article's title is a bit misleading though, midway through it says that it's only coming for a select few games, starting with WoW, instead of being generally available to everything that runs in Win7. So I'm not sure how exactly that's going to work. But who knows, we'll wait and see

**Comment by Vivero** [comment]
Please try @FeepingCreature suggestion; re-open if there are still issues.

**Comment by FeepingCreature** [comment]
Just to clarify: my experience is that it crashes after a minute with `--force-d3d11`.
