### ISSUE TITLE
N key is used for RCS translation.

### ISSUE THREAD

**Issue by WhirligigGirl** [Vivero/Kerbal-VR#3]
While I haven't yet had the chance to try this, the readme states:

"5. During flight, enter IVA, and press the 'N' key to initialize the HMD
6. You can press 'N' again to reset the default position"

Which is all well and good, except that the 'N' key is the key which is used for reverse translation (H is forward, and IJKL are sideways translations) for the staging mode.

**Comment by Vivero** [comment]
Good point, the choice of 'N' was arbitrary, didn't check to see if it's already bound to something. I'll change it to the 'Y' key. It looks like it's not bound to anything by default ('O' and 'P' could also work).
