### ISSUE TITLE
Orientation wrong in some Vessels

### ISSUE THREAD

**Issue by mrcheeze1** [Vivero/Kerbal-VR#33]
First: Amazing work! Thank you so much, I've been waiting for this for ages!

I've noticed that in some cockpits the orientation is rotated upwards (as if you're lying on the ground on your back). Examples are the ALCOR Landing Capsule and the Lander Can for 2 Kerbals.

Is there any way to fix this?

**Comment by Vivero** [comment]
I didn't realize certain capsules had a different internal orientation. Fixed! Closed via #34 
See latest release (v3.1.2).
