### ISSUE TITLE
External cameras in VR?

### ISSUE THREAD

**Issue by jeq1** [Vivero/Kerbal-VR#36]
I tested this mod and loved flying airplanes. But could you get so we can see mouse, and all stuff what is shown at monitor too, and to work at external cameras? I would love to play kerbal fully in VR without removing headset. World scale should be automatically at least 2, and it should save last used world scale. SPH movement around ship is painfully slow, speed should be adjusted by distance of finger from trackpad center.

**Comment by Vivero** [comment]
Good suggestions, yes. Let me think about it a little bit and I'll see what I can do, thanks for your input!

**Comment by jeq1** [comment]
alpha 4.00 getting there :P
