### ISSUE TITLE
Some bugs I've found

### ISSUE THREAD

**Issue by 9595w** [Vivero/Kerbal-VR#41]
In the editor, all textures are missing.
https://imgur.com/a/BOqHB0M

Unable to change the hand size option. Stuck at 2cm.
https://imgur.com/a/7tNU7E9

**Comment by Vivero** [comment]
The missing textures bug was unfortunately introduced by KSP 1.4 when Squad upgraded the Unity engine, and only appears when you run with DX12 (which KerbalVR requires). This [KSP forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/168795-electrocutors-thread/) talks about it, indicating to use [this fix](https://drive.google.com/open?id=1sb2_qyvBsBPrQFyGldK5x7uW2UJb14et).

I'm not sure about the hand size thing, its supposed to let you type in any integer between 1 and 10. I'll try to look into it, but I'm working on changing those "hands" entirely anyways. Into actual real hands.

**Comment by Vivero** [comment]
This issue is now OBE, due to #42. Closed.
