### ISSUE TITLE
Crash at startup after first launch of KSP

### ISSUE THREAD

**Issue by Cassio38** [Vivero/Kerbal-VR#43]
Hello,

I can launch KSP, play it in VR mode (using a shortcuts -force-d3d12) but when i close KSP it crash and then i cant start KSP anymore. right after the loading bar a crash occur.

config
win 10 pro 64
GTX 1080 - nvidia's drivers : 397.31
SteamVR & steamVR beta (steam VR non beta : 1525633672)
I7 2600k - 20 gb ram
KSP version 1.4.3.2152
KerbalVR 3.2.0

bonus
i dont think its related but while using -force-d3d12, parts in the part picker in VAB are blues.

**Comment by Cassio38** [comment]
here's some update.

i start with a vanilla version of the game, duplicate the folder, create the -force-d3d12 shortcuts, all work fine. at first i though adding any mod may cause the problem. so i installed ckan and tried a mod (mk1 stocklike open cockpit =D) no problems (except the remaning blue-picker-part thing caused by problem betweens texture and direct X 12)

and then, since KerbalVR require it, i installed Module Manager. still no problem

i turned steamVR on before launching KSP (but without KerbalVR installed), still ok

i tweak some graphics options (v-sync off, windowed, frame rate limit to 100, render on "goog"), still good.

Time to put KerbalVR into the Mosh Pit !

**Comment by Cassio38** [comment]
ok KerbalVR seems not detected. time to restart from scratch

**Comment by Cassio38** [comment]
tried downloading a vanilla. if i put KerbalVR + modulemanager (or any other mod) it crash before launching. if i put only KerbalVR, it boot once, i can play in VR but when i quit the game it crash and cant be launched again

**Comment by Vivero** [comment]
Could you upload a copy of the `KSP.log` file somewhere here so I can take a look? Sounds very strange, and it sounds like you're doing all the right things... :/

**Comment by Cassio38** [comment]
sure ! here it is !

[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2019402/KSP.log)

**Comment by d10sfan** [comment]
I had the same issue on the latest Kerbal from steam. I ended up installing ModuleManager.3.0.4 instead of 3.0.7 and that seemed to help for some reason.

**Comment by Vivero** [comment]
Unfortunately I can't tell much at all about why KSP is crashing for you... there's nothing in the log that stands out to me...

Did you try the suggestion of trying an older version of ModuleManager? You could also even just try without ModuleManager at all, and just see if it works. At a very minimum, KSP + KerbalVR (and no other mods) should just work out of the box, without crashing like you described.

**Comment by Vivero** [comment]
OBE
