### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by rocketstrong600** [Vivero/Kerbal-VR#46]
I have encountered a bug where the sky seems to be attached to the headset rotation only really shows when you move your head fast

**Comment by rocketstrong600** [comment]
i cant seem to reproduce the bug

**Comment by finlopes97** [comment]
I can also say that there's been some weird behavior with the sky. The moon seems to move with my head when I look around.

**Comment by Vivero** [comment]
Yea I _think_ I know what you mean... there's something subtle about the sky that looks strange. I'm not sure how to capture this behavior, much less fix it, whatever it is

**Comment by Dartans** [comment]
It only happens on the HMD too and not on the monitor so it's hard to capture.

**Comment by Vivero** [comment]
I think this is fixed now: [KerbalVR 3.2.6](https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.6)
