### ISSUE TITLE
Rotation Control - Roll

### ISSUE THREAD

**Issue by Zabbor** [Vivero/Kerbal-VR#47]
Been having an absolute blast using Kerbal VR

This might not be a actual issue but, i've noticed that Rotation Control is only Pitch and Jaw, not Pitch and Roll. Can't seem to find anyway to change it.

Been making a Mk1inline cockpit but its hard to control without roll.

**Comment by Vivero** [comment]
Yea it's currently hard-coded to control pitch and yaw... I need to make it configurable, perhaps in the part's .cfg file

**Comment by Vivero** [comment]
Added a configurable setting for this. Open up the KerbalVR GUI while in game, use the option `Swap Yaw/Roll Controls`.

**Comment by Vivero** [comment]
Closed via #77

**Comment by Vivero** [comment]
Latest release: https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.4
