### ISSUE TITLE
KSP shortcut invalid

### ISSUE THREAD

**Issue by TheNordicToast** [Vivero/Kerbal-VR#50]
When i try adding the "-force-d3d12" part to the ksp shortcut it wont work. I get a message saying the file doesn't exist and that i should check if the name is right. I double checked that i did exactly as told to do in the guide, all from the extraction to the shortcut. Could it be because i downloaded it through steam? 
Please help.

**Comment by Kerbas-ad-astra** [comment]
I had that issue when I put the `force-d3d12` flag inside the quote marks to the executable path (my KSP install path had some spaces in it).  The flag should be outside the quote marks, so the shortcut should look look something like: `"[path to exe with spaces]/KSP_x64.exe" -force-d3d12`

**Comment by TheNordicToast** [comment]
Okay thanks.
