### ISSUE TITLE
Nothing happens when i enable VR

### ISSUE THREAD

**Issue by yy344** [Vivero/Kerbal-VR#53]
I have SteamVR opened in beta, i have the  -force-d3d12 in the shortcut, i opened with the  shortcut, but nothing happens when i press the "enable vr" button, any fix for this?

**Comment by Vivero** [comment]
Not sure, if you attach a copy of the KSP.log here, that might give some insight as to what's happening

**Comment by yy344** [comment]
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2094386/KSP.log)
also i  just  realised when i try to move the kerbal vr thing it makes a bunch of copies  of it behind and the screen freezes

**Comment by Vivero** [comment]
I see you're running on Win8.1, which I've never really tested. Looks like KSP is running with Direct 3D 9 even though you correctly specified the d3d12 flag. I've a feeling Win8 is not supported for the same reason Win7 is not. Lack of directX12 support from the OS :(

**Comment by Vivero** [comment]
Duplicate issue #28
