### ISSUE TITLE
Possible 1.3.1 release?

### ISSUE THREAD

**Issue by 1greywind** [Vivero/Kerbal-VR#54]
Thank you dear Vivero for this excellent mod! I'm enjoying it very much under 1.4. But I also like to play RSS and my RSS setup still runs on 1.3.1 (many dependencies are not yet updated).

I verified that KerbalVR works on 1.0.1. So I've tried to recompile 1.0.1 release for 1.3.1 and it compiles without errors. But on 1.3.1 it fails to send video to my HTC VIVE - but head tracking in game works very well.

Could you please check if it possible to make old version to work on 1.3.1? Just sending video output to Vive will be enough.

**Comment by Vivero** [comment]
I tried for a long time to make it work on KSP 1.2.x and 1.3.x, but never got it to work. If I (or someone else) can come up with a solution that makes the mod work without DirectX 12, then it might work for KSP 1.3, maybe.

**Comment by 1greywind** [comment]
Thank you for replay @Vivero. Anyway, I'm enjoying your mod under 1.4. Thank you for great work!

**Comment by Vivero** [comment]
Likely not going to happen. Sorry
