### ISSUE TITLE
Crashes in 1.4.4

### ISSUE THREAD

**Issue by magicmellon** [Vivero/Kerbal-VR#55]
**Describe the bug**
When the button to swap to VR is clicked in KSP 1.4.4 the game screen freezez and VR sometimes hangs as if it is loading a game but normally just waits in the between game environment.

**To Reproduce**
1. Use KSP 1.4.4 with Steam VR running etc
2. load it all up
3. Go through and onto the runway
4. click the enter VR button

**Expected behavior**
Although im completely not expecting this to work on 1.4.4 i can no longer find a copy of 1.4.3 and thought it might be worth mentioning

**Log**
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2181470/KSP.log)

looks like an issue with the OpenVR file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - KSP Version: 1.4.4
 - VR Hardware: Vive

**Additional context**

**Comment by Vivero** [comment]
I believe you have a typo in your command line arguments. Your KSP.log shows you ran with
```
KSP_x64.exe - force-d3d12
```
it should be
```
KSP_x64.exe -force-d3d12
```
delete the space in between the first dash and "force-d3d12" (step 11 of the [Install Guide](https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide))
