### ISSUE TITLE
Black screen and infinite loading

### ISSUE THREAD

**Issue by yy344** [Vivero/Kerbal-VR#57]
I installed the new version of KerbalVR and when i did everything there was a black screen on startup, adding a folder named "Squad" into the GameData fixed this, but when its loading it never loads.
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2300299/KSP.log)

**Comment by Vivero** [comment]
From the log, it doesn't seem like you did step 9 from [install guide](https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide)
