### ISSUE TITLE
Game crashes on launch.

### ISSUE THREAD

**Issue by PhoxVRC** [Vivero/Kerbal-VR#58]
The game crashes on launch,

 - OS: Windows 10
 - KSP Version: 1.4.5
 - VR Hardware: Oculus

I think it might be because i have the latest Steam VR beta and cannot roll back to the working version.

[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2300466/KSP.log)

**Comment by Vivero** [comment]
Oh you know what, sometimes there is this stupid bug that crops up and makes the game freeze/crash during loading; can you try deleting this file in the `KerbalVR` mod folder:

```
GameData/KerbalVR/Assets/Props/Control/Push_Button_Modular/models/pb_Full_Cap_Black.png
```

It's like for some reason there are textures that refuse to load. Let me know how it goes.

**Comment by Vivero** [comment]
Side note, I'm not sure that the SteamVR beta version matters too much... last night I tested whatever the latest version was, and it seemed to be okay.

If deleting that file doesn't help, maybe you can try KerbalVR v3.2.0 (which I know is built for KSP 1.4.3, but try it on KSP 1.4.5 anyways, I think it should be fine)

**Comment by PhoxVRC** [comment]
Deleting the file did not help i will try KerbalVR v3.2.0

**Comment by PhoxVRC** [comment]
Even changing the version did not help but its showing a different error (since i sent the first log i have been removing mods to check if they where the problem so it looks a bit diffrent)
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2300490/KSP.log)

**Comment by A-FadedAway** [comment]
i am currently having the same problem, i have tried going back to 1.4.4, reinstalling the whole game, installing old kerbal vr versions, tried with the 32bit version, removing making history and messing with the steam vr versions and settings. nothing seems to work, the weird thing is that it used to work with kerbalvr v3.2.0 and version 1.4.4 but now it just doesn't.

**Comment by A-FadedAway** [comment]
i have no idea what i did but it suddenly started working
update: running in administrator mode was the solution

**Comment by PhoxVRC** [comment]
Alright,
I will try running it in administrator mode.

Edit: Administrator mode fixed it! Thanks a whole bunch!

**Comment by A-FadedAway** [comment]
great to know its working, took some time to find out.
