### ISSUE TITLE
Non issue: about implementation.

### ISSUE THREAD

**Issue by Aesop112** [Vivero/Kerbal-VR#6]
Is this Vr support for room scale and tracked controllers for the htc vive?

**Comment by Vivero** [comment]
It is configured as "seated mode", but if you have room-scale set up, there is no problem with getting up and moving around. You will move around inside the gamespace. Tracked controllers are still work-in-progress.

**Comment by Aesop112** [comment]
Very interested to try with the vive wands. How did you plan on implementing them?

**Comment by Vivero** [comment]
As of release v3.0.0, you can use the Vive controllers to move around inside the VAB / SPH.
In the next release, I plan on implementing cockpit props that can be grabbed and manipulated to control the craft (control sticks, throttle lever, switches, buttons).

**Comment by 9595w** [comment]
Hey vivero, in the next update is it possible to make the cockpit props that can be manipulated also work with the rasterpropmonitor mod? It would be great for full immersion, and btw your mod works great.

**Comment by Vivero** [comment]
Thanks I appreciate your support!

I agree, interacting with RPM would be amazing. Unfortunately, at least in the near future, I'm not sure I can hook up RPM to be interactive in VR; I have some further thoughts here: https://github.com/Vivero/Kerbal-VR/issues/5

**Comment by Vivero** [comment]
It's not a definite "no" to your request, but I'm continuing to think about what's possible, let's wait and see how the mod develops.

**Comment by jrbudda** [comment]
I'm not sure it would be all that hard. All the RPM 'buttons' are just unity objects and work off the Monobehaviour OnMouseDown/Up.

Is it not pretty simple to get a game object from the controller position and call MouseDown/Up ?

**Comment by Vivero** [comment]
That's what I thought too! I sunk a surprisingly large number of hours trying to figure out how to force a call on the MouseDown/Up function of the buttons, when the right conditions were met (controller position is close enough, or controller collider hits the button collider).

I honestly couldn't figure it out. The answer wasn't obvious to me; I would love a second pair of eyes to investigate how to do that.

**Comment by jrbudda** [comment]
I can totally do that. Do you have a version with the controller stuff in it coming?

**Comment by Vivero** [comment]
Yes I was planning on releasing something within the next week with some preliminary support for controllers and interactive props in IVA.

But if you want to jump right in, the `version-3` branch already has a ton of new code, might be a little rough on the documentation, but mainly has the implementation of controller GameObjects with colliders (at the moment... it's literally a Sphere primitive for each hand lol). If you compile the project in Debug mode in VisualStudio, you can jump right in IVA and see your hands (two little colored spheres).

**Comment by jrbudda** [comment]
Ah hadn't noticed the branch, perfect.

**Comment by Vivero** [comment]
[totally unrelated]
btw @jrbudda, great job on Vivecraft, I play it sometimes, it's really really amazing :)

**Comment by jrbudda** [comment]
you can now click on RMP buttons, tho the little spheres are kinda too big without scaling up the worldspace like in my master PR. I was gonna re-do that world scaling code better, should I do it on the master branch or version-3?

**Comment by Vivero** [comment]
Oh man that's awesome, hmm okay, could you do it on the version-3 branch?
Thanks so much!

**Comment by Vivero** [comment]
Closed via #27
