### ISSUE TITLE
Target box is not valid

### ISSUE THREAD

**Issue by E5oter1c** [Vivero/Kerbal-VR#61]
I wrote, "K:\GAME INSTALLATIONS\Steam\steamapps\common\Kerbal Space Program\KSP_x64.exe -force-d3d12" at the target box and this is what is said. It said, "The name "K:\GAME INSTALLATIONS\Steam\steamapps\common\Kerbal Space Program\KSP_x64.exe -force-d3d12" specified in the target box is not valid.". I need help!

**Comment by Vivero** [comment]
Move the double-quotes as follows:
`"K:\GAME INSTALLATIONS\Steam\steamapps\common\Kerbal Space Program\KSP_x64.exe" -force-d3d12`
