### ISSUE TITLE
How about 1.2.2 Release?

### ISSUE THREAD

**Issue by E5oter1c** [Vivero/Kerbal-VR#62]
### Hello

I only use 1.2.2 for mods and not any versions that are greater than 1.2.2. I mean, it doesn't mean that i never update, i just set the beta to 1.2.2. **Can you make a release for KSP 1.2.2?**

**Comment by Vivero** [comment]
Same as explanation as #54: I tried for a long time to make it work on KSP 1.2.x and 1.3.x, but never got it to work. If I (or someone else) can come up with a solution that makes the mod work without DirectX 12, then it might work for KSP 1.2, maybe.

Sorry! At least for now, it's unlikely for me that I'll come up with a working solution for 1.2.2.

**Comment by FeepingCreature** [comment]
I just want to note again that I could run it fine on Windows 7 with `--force-d3d11` on an NVidia GTX970, no significant issues aside the random crash after a bit.

I can post video if you don't believe me.

**Comment by Vivero** [comment]
If `--force-d3d11` is working for people on Win7, then I guess I'll close this issue. Thanks!

**Comment by Vivero** [comment]
Wait I think I confused this issue with something else. I don't think KSP 1.2.2 will work with KerbalVR even if you use the forced3d11 flag.

**Comment by Vivero** [comment]
Likely not going to happen. Sorry
