### ISSUE TITLE
Not Working On Latest Update

### ISSUE THREAD

**Issue by aseylys** [Vivero/Kerbal-VR#67]
I just did a clean re-install of KSP to 1.6. I also, just installed your latest version of Kerbal-VR. I followed the instructions to the "T", with executing the command `."C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64.exe" -force-d3d12` while SteamVR was running. Tried going into IVA mode then, but the icon to go VR isn't there. I've attached the log, but I think it might have something to do with the most recent update of SteamVR to 1.2.6.
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2729175/KSP.log)

**Comment by Vivero** [comment]
I don't think you installed the correct package. It seems you downloaded the source code package, or a copy of the repo or something. Please download this: https://github.com/Vivero/Kerbal-VR/releases/download/v3.2.2/KerbalVR_v3.2.2.zip

**Comment by Vivero** [comment]
https://github.com/Vivero/Kerbal-VR/wiki/Install-Guide

Verify `KerbalVR.dll` exists in `GameData\KerbalVR\KerbalVR.dll`. It did not get loaded, according to the log. This is also incorrect: `GameData\KerbalVR\lib\win32\openvr_api.dll`. These are not the correct paths to the `openvr_api.dll`. This is why I think you have the source code package, not the release files.
