### ISSUE TITLE
Laggy and choppy head movement

### ISSUE THREAD

**Issue by achurch333** [Vivero/Kerbal-VR#69]
FPS is fine, when I'm not moving and just watching other things move, it's very smooth. However, when I move my head and look around, it's very choppy and sometimes freezes for a very short moment and catches up. It's not a major problem but it makes me dizzy if I move my head too fast. If I move my head slowly there's no lag/freezing. I've cranked all the settings down to the bare minimum however it seems to have made no difference.

CPU is a Ryzen 2600, GPU is a GTX 1070, 8GB of RAM, using a Windows MR headset which may be the problem.

**Comment by Vivero** [comment]
yikes, that's disappointing. i haven't had a chance to test things too much since the 1.6 update, performance is unfortunately something I can't really control; I'll need to do some testing, thanks for the input

**Comment by samamstar** [comment]
I have been having this issue as well. Turning off steamVR motion smoothing seems to fix it. Though I do still have a bit of jitter afterwards, it is certainly reduced

**Comment by Vivero** [comment]
Please re-open if it's still an issue on the latest versions of KSP and KerbalVR.
