### ISSUE TITLE
tracking works, but vive shows default scene

### ISSUE THREAD

**Issue by SirDavid12** [Vivero/Kerbal-VR#7]
I installed everything correctly, on ksp 1.1.3 it worked, also with a gtx 980 on low at 90 fps, and now in 1.2 the tracking works, the gamewindow shows one eye, and when i move the headset it works too but the display in the headset just shows the normal this is real scene

**Comment by Vivero** [comment]
Yep, I'm seeing the same behavior in 1.2, good to know at least one other reporting the same thing. I thought a re-compile against the 1.2 libs would fix it, but it doesn't.

The vrCompositor.Submit function calls are throwing some error that I cannot explain or fix (that function is supposed to send the rendered frames to the headset display). I'm bit stumped on this one... I'll keep trying some things, but _any_ help is appreciated.

**Comment by SirDavid12** [comment]
Sorry for the late response,

I happen to be a VR game developer myself, and I'd reallly like to play ksp in vr, so maybe I could take a look at it as well.

**Comment by SirDavid12** [comment]
Ok so I looked at your code and I recognize some steamVR Plugin scripts, but I have no Idea how to write mods for ksp, so I'd really like to help, but You'd have to explain some of your code to me, my background knowlage is about 600 hours Unity + steamVR

**Comment by dpmorrow** [comment]
I noticed that if you set it to EGraphicsAPIConvention.API_DirectX again and launch with -force-d3d11 flag you can get it working for a few seconds before rendering blows up.  Although rendering is flipped on one eye...

Just thought I'd share since I've been poking it for a few hours now 😄

**Comment by X52p** [comment]
I have the same problem.
Is there any Information about my setup that could help you?

**Comment by jrbudda** [comment]
I've been poking at this for a while now too, found the following:
KSP 1.2 is Unity 5.4 and defaults to Direct3d 9.

SteamVR does not accept textures in d3d9 format. In Unity 5.4 the 'legacy OpenGL' backend was removed in favor of 'opengl-core'. Found a random forum post that explains SteamVR only works with the legacy OpenGL from Unity < 5.4. So that's why the mod breaks in 1.2.

Current only option then is -force-d3d11 tho I haven't got that working either, the whole game locks up on compositor.submit for me.

**Comment by adigyran** [comment]
So, no progress here?

**Comment by jrbudda** [comment]
I haven't tried again tbh, the only way this could possibly work is if the newer unity still supports the older unity render thread VR events but I doubt it and I haven't tried it that way.

**Comment by adigyran** [comment]
so, no luck after month? i`m dying to try this with my htc vive. but reverting the version means reinstalling all hell of mods

**Comment by X52p** [comment]
Hi, I tried using an injector designed for Unity: https://github.com/Eusth/VRGIN it doesn't work in KSP for other reasons, but it has the exact same problem in any other Unity game I tested when Mirror display (displaying on HMD and normal Monitor) is enabled. Maybe that's a place to look for the problem. I hope this information is useful in some way.
I would really like to play the newer KSP versions in VR.

**Comment by ZNixian** [comment]
If you use dxcpl to break on corruption (and add KSP to the scope), you'll get a crash as soon as you enter IVA. The subsequent minidump file turns up something inside vrclient_x64.dll (SteamVR).

**Comment by ZNixian** [comment]
I suspect I'll be able to fix this - I've gone from crashing to rendering a fully black screen.

**Comment by ZNixian** [comment]
Nevermind, I accidentally suppressed the issue, rather than fixing it.

**Comment by X52p** [comment]
I tried using DirectX 11, but I get an Access violation on submit. Has somebody an idea if i have to explicitly acquire access to the texture when using DirectX? Do I have to wait for a special event before submitting?

**Comment by ZNixian** [comment]
@X52p This is the same issue I was getting. I suspect it's a multi-threading problem, so you'll need to call SubmitFrame on the render thread.

**Comment by X52p** [comment]
I got it working again! Still, have some errors to fix and code to clean up (there was a lot trial and error)
If that's OK I will push that into a new Repository because a lot of the code needed to be rewritten to work in the new Unity Version. I'm also planning to maintain it in the Future.

**Comment by ZNixian** [comment]
How did you end up doing that? I tried using a C++ plugin to handle multi-threading, but that didn't end up working.

Kerbal-VR is under the MIT license; you can do whatever you want with it, without asking anyone, by the way.

**Comment by Poldor** [comment]
@X52p great work. Looking forward to your release and to learn how you did it!

**Comment by Ermintrude-the-cow** [comment]
Superb, thank you! Looking forward to trying it out.


________________________________

**Comment by Vivero** [comment]
@X52p impressive! I would also love to see how you did it! And yes feel free to do as you please with the code.

**Comment by jrbudda** [comment]
I would very much like to contribute to this if it's working.

**Comment by X52p** [comment]
I have pushed everything I made into a new repository: https://github.com/X52p/KerbinReality
Currently I have performance issues. It would be really nice, if You have any Idea how to solve them. (and sorry that the code is such a mess at the moment)

**Comment by ZNixian** [comment]
I'll have a look.

**Comment by Vivero** [comment]
So uhh... I might've fixed this problem. I don't know how this works. But I updated all the OpenVR libraries and SteamVR Unity plugin scripts, then I simply ran KSP with the -force-d3d12 flag. The frames get rendered correctly to the headset, except now the orientation of the headset is wrong in the game, i.e. if I look up, the camera looks down and vice versa.

I put all these changes in the `updated-openvr` branch, but I won't release a new version until I fix the obnoxious orientation issue (I'm sure it's gotta be some simple math change somewhere).

**Comment by Ermintrude-the-cow** [comment]
Thanks for the update - I love that you're doing this. Can't wait to see a working version!



________________________________

**Comment by Vivero** [comment]
Incredible. For some silly reason, to fix the orientation issues, I needed to flip the vertical coordinate of the render texture. Perhaps running with DirectX 12 necessitated this. Anyways, the mod works on KSP v1.4 now. Closing with #15. Thank you to everyone for your contributions to this conversation. Cheers!

**Comment by dpmorrow** [comment]
Excellent work!

I just got stands for my lighthouses finally and was considering starting a new VR project, or even finishing one of my others

I was thinking though, does it seem plausible to inject the VR context at other times such as in the KSP facility screen and the various buildings?

Obviously if that's possible it'll take a lot of work to redesign the interfaces to be VR friendly, but how cool would that be!?

On that note, I'm wondering if considering these blockers have been removed, it's time to start a kanban board and make it clear the objectives of the project so we can start contributing towards common goals?

It would seem there's a few lurkers on this thread like myself that might want to help now.

**Comment by Vivero** [comment]
Thanks for the suggestions! It is certainly possible to allow VR in the other buildings, I've been experimenting with implementing room-scale VR in the VAB, and it seems feasible (but there are quirks).

I'm overhauling a lot of the code in order to allow for more features. I'd like to focus on the aspect of VR-friendly interfaces; how do we control craft from IVA, how to build in the VAB/SPH, etc.

A kanban board sounds like a cool idea; let me gauge how the project is going first before I jump ahead towards that idea. Thanks for following along, I appreciate the enthusiasm 😁
