### ISSUE TITLE
Everything glitches out when you remove your headset.

### ISSUE THREAD

**Issue by pwncc** [Vivero/Kerbal-VR#70]
Some OPENGL thing. It also does this with minecraft when textures are not loaded correctly.

To reproduce:
Remove your headset and leave for a while. keep doing it until it glitches out.

**Comment by pwncc** [comment]
![image](https://user-images.githubusercontent.com/32709410/52225838-a4264180-28ab-11e9-8abb-7ee82f0ca23d.png)

**Comment by pwncc** [comment]
Can confirm that it does not only happen when removing the headset. It happens at random times too
[output_log.txt](https://github.com/Vivero/Kerbal-VR/files/2829152/output_log.txt)

**Comment by pwncc** [comment]
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component:get_transform ()
  at FlightCamera.SetDistanceImmediate (Single dist) [0x00000] in <filename unknown>:0 
  at MapView.OnDestroy () [0x00000] in <filename unknown>:0

**Comment by pwncc** [comment]
it happens pretty often with any cockpit and is extremely frustrating due to loading times

**Comment by pwncc** [comment]
![image](https://user-images.githubusercontent.com/32709410/55188266-3e638100-519b-11e9-852e-4bfdfe6ff0ce.png)

**Comment by Vivero** [comment]
Yea something seems to be going bonkers in your situation. If it happens again, post a link to your `KSP.log` and maybe I can see what's going on.

**Comment by Vivero** [comment]
Closed until further information is provided.
