### ISSUE TITLE
KSP Crashes on "Loading" Screen

### ISSUE THREAD

**Issue by The-VROfficer** [Vivero/Kerbal-VR#72]
I've seen this bug similar to this mentioned before, so I'm not sure if this is different. Every time that I open the game off of the KSP_x64.exe file that has the "-force-d3d12" extension on it, the game gets stuck on the loading screen (after it loads all the files up and just says "loading" in the bottom right, nothing else) and crashes. I'm not sure why it's doing this, since I've installed all the proper stuff. I'd appreciate any help I can get.

**Log**
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2933903/KSP.log)

 - OS: Windows 10 (v1803)
 - KSP Version: 1.4.3.2152 / 1.6.1
 - VR Hardware: Vive
 - Kerbal-VR Version: 3.2.2

**Comment by Vivero** [comment]
Strange, I can't really tell what went wrong from the KSP.log. Have you tried running with only the KerbalVR mod, see if it works, then start adding other mods one by one until it breaks?

**Comment by The-VROfficer** [comment]
Tried running it in Administrator Mode (through the right click menu) and that seemed to fit! Still testing it, but I think doing that only once may have made it so it doesn't crash any more.
