### ISSUE TITLE
when in the vab/sph parts dont have textures when launched from the shortcut.

### ISSUE THREAD

**Issue by tcd77** [Vivero/Kerbal-VR#73]
everything else is fine and i can just build crafts regularly from the regular launcher but not the shortcut.

**Comment by Vivero** [comment]
The [readme](https://github.com/Vivero/Kerbal-VR/blob/master/README.md) tells you how to fix it.

Although in KSP 1.7, the fix is not 100% effective.

**Comment by Vivero** [comment]
This is actually something funky with the way the game runs in DirectX 12. Nothing I can do to fix it though, and is unrelated to the KerbalVR mod.
