### ISSUE TITLE
Update to 1.7? Progress check?

### ISSUE THREAD

**Issue by 9595w** [Vivero/Kerbal-VR#74]
Hey! I love this mod that is being developed, I was wondering if this mod was still in development too. 1.7 came out not too long ago, so it would be great if it could get released any time soon. The mod looks great, keep up the good work!

I run with a Samsung Windows Mixed Reality headset.
I7 4790k processor.
GTX 1070 Founder's Edition.
Good FPS, Low settings.

**Comment by Vivero** [comment]
Oh nice! Thanks for letting me know, I didn't realize it already came out. I think I can at least re-build the mod for 1.7 this weekend. Shouldn't be too hard. I know there are other outstanding issues but I may not be able to address those. Stay tuned

**Comment by 9595w** [comment]
Thanks for that. Something useful would be an adjustable hand size option if possible.

**Comment by Vivero** [comment]
> Thanks for that. Something useful would be an adjustable hand size option if possible.

Agreed, I hope to get around to making this happen soon.

**Comment by Vivero** [comment]
Closed via [new release](https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.3)
