### ISSUE TITLE
WMR hands/controllers aren't visible

### ISSUE THREAD

**Issue by ghost** [Vivero/Kerbal-VR#75]
The Windows Mixed Reality controllers do not show up.
I have tried simple SteamVR and Beta Update version. 
With the game version 1.4.1 / 1.4.3 and the latest version 1.7 of the game. 
I tried to turn them on even after loading the game or after being entered into VAT.
I noticed, however, that the menu button on the controller resets the view.

 - OS: Windows 10 x64
 - KSP Version: 1.4.1/1.4.3/1.7.*]
 - VR Hardware: Windows Mixed Reality "Lenovo Explorer"
 - Kerbal-VR Version: v3.2.3

**Comment by Vivero** [comment]
I think I fixed this via #77 

If you still see issues, provide a link to the `KSP.log` file.

**Comment by Vivero** [comment]
i.e. try the latest version of the mod https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.4
