### ISSUE TITLE
Screen not being redrawn correctly

### ISSUE THREAD

**Issue by linecrafter** [Vivero/Kerbal-VR#79]
I dont know what i did exactly but it started doing that after i checked out the VAB VR , played with world scale and tried to launch while inside VAB vr
Video clip: https://i.imgur.com/SoLHLXq.gifv

[KSP.log](https://github.com/Vivero/Kerbal-VR/files/3365900/KSP.log)

Oculus Rift, Touch Controllers

**Comment by linecrafter** [comment]
also giving you credit for updating the mod to latest ksp versions

**Comment by linecrafter** [comment]
rebooting pc solved the issue

**Comment by jkurupt** [comment]
Yeah I figured It's a hit and miss. It happens though when I click it twice.

**Comment by jeancallisti** [comment]
I would suggest changing this issue's title to "GUI overlay not being erased from screen before being redrawn"
