### ISSUE TITLE
Kerbals in View

### ISSUE THREAD

**Issue by X52p** [Vivero/Kerbal-VR#8]
Depending on my Head position the eyes Kerbal that is sitting on my chair are in view.
It would be nice if it was possible to set the Kerbal invisible.
Also the ability to manually set the scale in VR would be really useful.

**Comment by Vivero** [comment]
Is this still an issue? When I go into VR, the Kerbal's head is not even rendered. Just the body (a decapitated body 🤣)

**Comment by robotnia** [comment]
It works well now

**Comment by Vivero** [comment]
Closing due to O.B.E.
