### ISSUE TITLE
(Valve Index) (Suggestion) Hands Support?

### ISSUE THREAD

**Issue by 9595w** [Vivero/Kerbal-VR#83]
Hey! Hope this mod is still getting updated. I think it would be cool if hands from the index controllers could be implemented? Also with all of these new controllers having joysticks, I'm not sure if it's possible to maybe implement them as axis (pitch, yaw, roll) instead of using the cockpit controls. I've always found that joystick hard to use. Anyways, great work on the mod!

Windows 10
KSP Version: [1.7.3]
Valve Index
Kerbal-VR Version: [3.2.4]

**Comment by jeancallisti** [comment]
Have you tried explicitly mapping the controllers' joysticks to KSP controls in the settings menu? I'd be surprised if Windows didn't just register them as joysticks.

**Comment by 9595w** [comment]
Thanks, almost forgot I could do that. It would be great though to have finger tracking in kerbal. Also ive heard that the new 1.8 update has a unity update in it so I believe, for this mod at least there will be a performance increase. Any way to make the mod faster would be nice.

**Comment by Vivero** [comment]
I got an Index recently and am working on revamping the mod from the ground up (it's the development branch named *restructured* if anyone is interested in building it for themselves). KSP version 1.9 uses a new version of Unity (or maybe that was introduced in 1.8 as you said), and I am getting **significant** perf gains by taking advantage of multi-threaded rendering in the new Unity version (KSP is using Direct3D11 by default now, without any need for the hacky flags). It's going to be a lot of work to release a new version of the mod, but so far it really is looking promising.

Btw the latest version of the mod I [released](https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.6) for KSP 1.9 is crashing way too much, it's completely unstable. The new work I'm doing is 100% stable and achieves much higher framerates (but still keep your gfx settings low 😉).

I'll also be taking advantage of the SteamVR input system, which should help facilitate controller bindings and all that. AND easily allows for finger tracking of course, which is amazing 😀

I agree that using the joysticks on the VR controller is probably a better way to control the craft. That virtual stick truly is difficult to manipulate carefully.

**Comment by Vivero** [comment]
I believe the [latest version](https://github.com/Vivero/Kerbal-VR/releases/tag/v4.0.0-alpha.3) addresses all the comments in this thread. Closing the issue for now. Please feel free to re-open if necessary, or if you have further feedback.
