### ISSUE TITLE
Explain better how OpenVR is used

### ISSUE THREAD

**Issue by jeancallisti** [Vivero/Kerbal-VR#87]
EDIT: Most issues with "Windows Reality Portal for Steam VR" were fixed after the latest big Windows 10 update.
They introduced a new annoying thing (by design! :-S )that the game is quitting when you go back to the VR hub, but apart from that the whole thing is much more stable.
I also found a registry key that lets me extend the tie before the VR headset goes to sleep (which was previously crashing or exiting the game)

**Comment by Vivero** [comment]
I don't understand, what is the issue here?

**Comment by jeancallisti** [comment]
There is no longer an issue if you upgrade Windows Reality Portal to the latest version and if you use the registry to expand the time after which it goes to sleep (it causes Kerbal VR to crash)
